"""Core domain types and schemas for chatflow-agent."""

from datetime import datetime, timezone
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class Role(str, Enum):
    """Message sender role."""

    USER = "user"
    MODEL = "model"
    SYSTEM = "system"
    TOOL = "tool"


class ToolCall(BaseModel):
    """Represents a tool invocation requested by the model."""

    id: str = Field(description="Unique identifier for the tool call")
    name: str = Field(description="Name of the function to invoke")
    args: dict[str, Any] = Field(default_factory=dict, description="Arguments passed to the tool")


class ToolResult(BaseModel):
    """Result returned from executing a tool."""

    tool_call_id: str = Field(description="ID of the tool call this result corresponds to")
    name: str = Field(description="Name of the tool executed")
    content: Any = Field(description="Returned content or payload from the tool execution")
    is_error: bool = Field(default=False, description="Whether the tool execution failed")


class Handoff(BaseModel):
    """Signal indicating a conversation transfer from the current agent to a target agent."""

    target_agent_name: str = Field(description="Name of the target agent to hand off to")
    reason: str | None = Field(default=None, description="Reason or intent for transferring the dialogue")
    context_updates: dict[str, Any] = Field(default_factory=dict, description="Variables or state to pass forward")


class Message(BaseModel):
    """Dialogue turn within a conversation session."""

    role: Role = Field(description="The role of the message participant")
    content: str | None = Field(default=None, description="Textual body of the message")
    tool_calls: list[ToolCall] | None = Field(default=None, description="Tools invoked in this turn")
    tool_results: list[ToolResult] | None = Field(default=None, description="Tool results returned in this turn")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp of creation",
    )


class AgentResponse(BaseModel):
    """Output payload from an agent execution turn."""

    content: str = Field(description="Final textual answer generated by the agent")
    active_agent_name: str = Field(description="Name of the agent currently handling the conversation")
    tool_calls_executed: list[str] = Field(
        default_factory=list, description="Names of tools executed during this turn"
    )
    handoff: Handoff | None = Field(default=None, description="Handoff details if a transfer occurred")
